export enum InflectionTableItemType {
  OPENING_BRACKET = 'OPENING_BRACKET',
  CLOSING_BRACKET = 'CLOSING_BRACKET',
  TIME_INDICATION = 'TIME_INDICATION',
  SPACE = 'SPACE',
  MASTER_ENTRY = 'MASTER_ENTRY',
  INFLECTED_ENTRY = 'INFLECTED_ENTRY',
  PLACEHOLDER_ENTRY_TRUE = 'PLACEHOLDER_ENTRY_TRUE',
  PLACEHOLDER_ENTRY_FALSE = 'PLACEHOLDER_ENTRY_FALSE',
  COMMENT = 'COMMENT'
}
