export enum InflectionTableItemType {
  OPENING_BRACKET,
  CLOSING_BRACKET,
  TIME_INDICATION,
  SPACE,
  MASTER_ENTRY,
  INFLECTED_ENTRY,
  PLACEHOLDER_ENTRY_TRUE,
  PLACEHOLDER_ENTRY_FALSE,
  COMMENT
}
